---
# Security tasks for targets.
# Based on dev-sec security baseline
- name: Install necessary packages for tracing
  package:
    state: present
    name: "{{ item }}"
  loop: "{{ dev_sec_prerequisites[ansible_os_family | lower] }}"
  register: sec_pkgs
  until: not sec_pkgs.failed
  retries: 2

- name: Secury kernel parameters
  sysctl:
    name: "{{ item.name }}"
    reload: true
    state: present
    sysctl_set: true
    ignoreerrors: false
    value: "{{ item.value }}"
  loop: "{{ sysctl_security_items }}"
