---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure python3
      raw: "sudo apt-get update -qq && apt-get install -y python3"
- name: Converge
  become: true
  hosts: all
  roles:
    - role: ansible-role-molecule-test-agent
      pre_tasks:
        - name: Update apt cache
          package:
            name: python3-minimal
            state: present
            update_cache: true
