---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ubuntu-18.10
    image_owner: 099720109477
    # image: ami-0b6f46ba4d94838a0
    image_name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
    instance_type: t2.medium
    vpc_subnet_id: subnet-45fc2708
    instance_tags:
      - Name: "molecule-test-instance"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["305,301"]

verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: "E501"
  options:
    junit-xml: junit.xml
    n: 5
