---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ubuntu-18.10-instance
    image: ami-0718a1ae90971ce4d
    instance_type: t2.medium
    vpc_subnet_id: subnet-91a4d6fa
    instance_tags:
      - Name: "molecule"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["305,301"]

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    junit-xml: junit.xml
    n: 20
  directory: ../default/
