---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && DEBIAN_FRONTEND=noninteractive apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false
