---
optional_packages:
  - command-not-found
  - command-not-found-data
  - eatmydata
  - fontconfig
  - fontconfig-config
  - fonts-dejavu-core
  - fonts-dejavu-extra
  - fonts-lato
  - fonts-ubuntu-console
  - friendly-recovery
  - ftp
  - htop
  - humanity-icon-theme
  - guile-2.0-libs
  - landscape-common
  - keyboard-configuration
  - plymouth
  - plymouth-theme-ubuntu-text
  - po-debconf
  - zerofree
  - zip
required_packages:
  - accountsservice
  - acl
  - acpid
  - adduser
  - apparmor
  - apt
  - apt-transport-https
  - apt-utils
  - at
  - at-spi2-core
  - aufs-tools
  - autoconf
  - automake
  - autopoint
  - autotools-dev
  - base-files
  - base-passwd
  - bash
  - bash-completion
  - bc
  - bcache-tools
  - bind9-host
  - binutils
  - binutils-common:amd64
  - binutils-x86-64-linux-gnu
  - bsdmainutils
  - bsdutils
  - btrfs-progs
  - btrfs-tools
  - build-essential
  - busybox-initramfs
  - busybox-static
  - bzip2
  - ca-certificates
  - ca-certificates-java
  - cgroupfs-mount
  - cloud-guest-utils
  - cloud-init
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - console-setup
  - console-setup-linux
  - containerd.io
  - coreutils
  - cpio
  - cpp
  - cpp-7
  - cron
  - cryptsetup
  - cryptsetup-bin
  - cups-bsd
  - cups-client
  - cups-common
  - curl
  - dash
  - dbus
  - debconf
  - debconf-i18n
  - debhelper
  - debianutils
  - debugedit
  - default-jdk
  - default-jdk-headless
  - default-jre
  - default-jre-headless
  - dh-autoreconf
  - dh-python
  - dh-strip-nondeterminism
  - diffutils
  - dirmngr
  - distro-info-data
  - dmeventd
  - dmidecode
  - dmsetup
  - dns-root-data
  - dnsmasq-base
  - dnsutils
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - dosfstools
  - dpkg
  - dpkg-dev
  - e2fsprogs
  - ebtables
  - ed
  - eject
  - ethtool
  - fakeroot
  - fdisk
  - file
  - findutils
  - fuse
  - g++
  - g++-7
  - gawk
  - gcc
  - gcc-7
  - gcc-7-base
  - gcc-8-base
  - gdisk
  - geoip-database
  - gettext
  - gettext-base
  - gir1.2-glib-2.0
  - git
  - git-man
  - gnupg
  - gnupg-l10n
  - gnupg-utils
  - gnupg2
  - golang-docker-credential-helpers
  - gpg
  - gpg-agent
  - gpg-wks-client
  - gpg-wks-server
  - gpgconf
  - gpgsm
  - gpgv
  - grep
  - groff-base
  - grub-common
  - grub-gfxpayload-lists
  - grub-legacy-ec2
  - grub-pc
  - grub-pc-bin
  - grub2-common
  - gzip
  - hdparm
  - hibagent
  - hostname
  - info
  - init
  - init-system-helpers
  - initramfs-tools
  - initramfs-tools-bin
  - initramfs-tools-core
  - install-info
  - intltool-debian
  - iproute2
  - iptables
  - iputils-ping
  - iputils-tracepath
  - irqbalance
  - isc-dhcp-client
  - isc-dhcp-common
  - iso-codes
  - java-common
  - javascript-common
  - jq
  - kbd
  - klibc-utils
  - kmod
  - krb5-locales
  - language-selector-common
  - less
  - libaccountsservice0
  - libacl1
  - libalgorithm-diff-perl
  - libalgorithm-diff-xs-perl
  - libalgorithm-merge-perl
  - libapparmor1
  - libapt-inst2.0
  - libapt-pkg5.0
  - libarchive-cpio-perl
  - libarchive-zip-perl
  - libarchive13
  - libargon2-0
  - libasan4
  - libasn1-8-heimdal
  - libasound2
  - libasound2-data
  - libassuan0
  - libatk-bridge2.0-0
  - libatk-wrapper-java
  - libatk-wrapper-java-jni
  - libatk1.0-0
  - libatk1.0-data
  - libatm1
  - libatomic1
  - libatspi2.0-0
  - libattr1
  - libaudit-common
  - libaudit1
  - libavahi-client3
  - libavahi-common-data
  - libavahi-common3
  - libbind9-160
  - libbinutils
  - libblkid1
  - libbsd0
  - libbz2-1.0
  - libc-bin
  - libc-dev-bin
  - libc6
  - libc6-dev
  - libcap-ng0
  - libcap2
  - libcap2-bin
  - libcc1-0
  - libcilkrts5
  - libcom-err2
  - libcroco3
  - libcryptsetup12
  - libcups2
  - libcupsfilters1
  - libcupsimage2
  - libcurl3-gnutls
  - libcurl4
  - libdb5.3
  - libdbus-1-3
  - libdebconfclient0
  - libdevmapper-event1.02.1
  - libdevmapper1.02.1
  - libdns-export1100
  - libdns1100
  - libdpkg-perl
  - libdrm-amdgpu1
  - libdrm-common
  - libdrm-intel1
  - libdrm-nouveau2
  - libdrm-radeon1
  - libdrm2
  - libdw1
  - libeatmydata1
  - libedit2
  - libelf1
  - liberror-perl
  - libestr0
  - libevent-2.1-6
  - libexpat1
  - libexpat1-dev
  - libext2fs2
  - libfakeroot
  - libfastjson4
  - libfdisk1
  - libffi6
  - libfile-fcntllock-perl
  - libfile-stripnondeterminism-perl
  - libfontconfig1
  - libfontenc1
  - libfreetype6
  - libfribidi0
  - libfuse2
  - libgc1c2
  - libgcc-7-dev
  - libgcc1
  - libgcrypt20
  - libgdbm-compat4
  - libgdbm5
  - libgdk-pixbuf2.0-0
  - libgeoip1
  - libgif7
  - libgirepository-1.0-1
  - libgl1
  - libgl1-mesa-dri
  - libgl1-mesa-glx
  - libglapi-mesa
  - libglib2.0-0
  - libglib2.0-data
  - libglvnd0
  - libglx-mesa0
  - libglx0
  - libgmp-dev
  - libgmp10
  - libgmpxx4ldbl
  - libgnutls30
  - libgomp1
  - libgpg-error0
  - libgpm2
  - libgsasl7
  - libgssapi-krb5-2
  - libgssapi3-heimdal
  - libgtk2.0-0
  - libgtk2.0-common
  - libhcrypto4-heimdal
  - libheimbase1-heimdal
  - libheimntlm0-heimdal
  - libhogweed4
  - libhx509-5-heimdal
  - libice-dev
  - libice6
  - libicu60
  - libidn11
  - libidn2-0
  - libip4tc0
  - libip6tc0
  - libiptc0
  - libirs160
  - libisc-export169
  - libisc169
  - libisccc160
  - libisccfg160
  - libisl19
  - libisns0
  - libitm1
  - libjbig0
  - libjpeg-turbo8
  - libjpeg8
  - libjq1
  - libjs-jquery
  - libjson-c3
  - libk5crypto3
  - libkeyutils1
  - libklibc
  - libkmod2
  - libkrb5-26-heimdal
  - libkrb5-3
  - libkrb5support0
  - libksba8
  - libkyotocabinet16v5
  - liblcms2-2
  - libldap-2.4-2
  - libldap-common
  - libllvm9
  - liblocale-gettext-perl
  - liblsan0
  - libltdl-dev
  - libltdl7
  - liblua5.2-0
  - liblvm2app2.2
  - liblvm2cmd2.02
  - liblwres160
  - liblxc-common
  - liblxc1
  - liblz4-1
  - liblzma5
  - liblzo2-2
  - libmagic-mgc
  - libmagic1
  - libmail-sendmail-perl
  - libmailutils5
  - libmnl0
  - libmount1
  - libmpc3
  - libmpdec2
  - libmpfr6
  - libmpx2
  - libmspack0
  - libmysqlclient20
  - libncurses5
  - libncursesw5
  - libnetfilter-conntrack3
  - libnettle6
  - libnewt0.52
  - libnfnetlink0
  - libnghttp2-14
  - libnih1
  - libnpth0
  - libnspr4
  - libnss-systemd
  - libnss3
  - libntfs-3g88
  - libntlm0
  - libnuma1
  - libonig4
  - libp11-kit0
  - libpam-cap
  - libpam-modules
  - libpam-modules-bin
  - libpam-runtime
  - libpam-systemd
  - libpam0g
  - libparted2
  - libpcap0.8
  - libpci3
  - libpciaccess0
  - libpcre3
  - libpcsclite1
  - libperl5.26
  - libpipeline1
  - libplymouth4
  - libpng16-16
  - libpolkit-agent-1-0
  - libpolkit-backend-1-0
  - libpolkit-gobject-1-0
  - libpopt0
  - libprocps6
  - libpsl5
  - libpthread-stubs0-dev
  - libqrencode3
  - libquadmath0
  - libreadline5
  - libreadline7
  - libroken18-heimdal
  - librpm8
  - librpmbuild8
  - librpmio8
  - librpmsign8
  - librtmp1
  - libsasl2-2
  - libsasl2-modules
  - libsasl2-modules-db
  - libseccomp2
  - libsecret-1-0
  - libsecret-common
  - libselinux1
  - libsemanage-common
  - libsemanage1
  - libsensors4
  - libsepol1
  - libsigsegv2
  - libslang2
  - libsm-dev
  - libsm6
  - libsmartcols1
  - libsqlite3-0
  - libss2
  - libssl-dev
  - libssl1.0.0
  - libssl1.1
  - libstdc++-7-dev
  - libstdc++6
  - libsys-hostname-long-perl
  - libsystemd0
  - libtasn1-6
  - libtext-charwidth-perl
  - libtext-iconv-perl
  - libtext-wrapi18n-perl
  - libtiff5
  - libtimedate-perl
  - libtinfo5
  - libtool
  - libtsan0
  - libubsan0
  - libudev1
  - libunistring2
  - libunwind8
  - libusb-1.0-0
  - libutempter0
  - libuuid1
  - libuv1
  - libwind0-heimdal
  - libwrap0
  - libx11-6
  - libx11-data
  - libx11-dev
  - libx11-doc
  - libx11-xcb1
  - libxau-dev
  - libxau6
  - libxaw7
  - libxcb-dri2-0
  - libxcb-dri3-0
  - libxcb-glx0
  - libxcb-present0
  - libxcb-shape0
  - libxcb-sync1
  - libxcb1
  - libxcb1-dev
  - libxcomposite1
  - libxdamage1
  - libxdmcp-dev
  - libxdmcp6
  - libxext6
  - libxfixes3
  - libxft2
  - libxi6
  - libxinerama1
  - libxml2
  - libxmlsec1
  - libxmlsec1-openssl
  - libxmu6
  - libxmuu1
  - libxpm4
  - libxrandr2
  - libxrender1
  - libxshmfence1
  - libxslt1.1
  - libxt-dev
  - libxt6
  - libxtables12
  - libxtst6
  - libxv1
  - libxxf86dga1
  - libxxf86vm1
  - libyaml-0-2
  - libzstd1
  - linux-aws
  - linux-aws-headers-4.15.0-1043
  - linux-aws-headers-4.15.0-1060
  - linux-base
  - linux-headers-4.15.0-1043-aws
  - linux-headers-4.15.0-1060-aws
  - linux-headers-aws
  - linux-image-4.15.0-1043-aws
  - linux-image-4.15.0-1060-aws
  - linux-image-aws
  - linux-libc-dev
  - linux-modules-4.15.0-1043-aws
  - linux-modules-4.15.0-1060-aws
  - locales
  - login
  - logrotate
  - lsb-base
  - lsb-core
  - lsb-invalid-mta
  - lsb-release
  - lsb-security
  - lshw
  - lsof
  - ltrace
  - lvm2
  - lxcfs
  - lxd
  - lxd-client
  - m4
  - mailutils
  - mailutils-common
  - make
  - man-db
  - manpages
  - manpages-dev
  - mawk
  - mdadm
  - mime-support
  - mlocate
  - mount
  - mtr-tiny
  - multiarch-support
  - mysql-common
  - nano
  - ncurses-base
  - ncurses-bin
  - ncurses-term
  - net-tools
  - netbase
  - netcat-openbsd
  - netplan.io
  - networkd-dispatcher
  - nplan
  - ntfs-3g
  - open-iscsi
  - open-vm-tools
  - openjdk-11-jdk
  - openjdk-11-jdk-headless
  - openjdk-11-jre
  - openjdk-11-jre-headless
  - openssh-client
  - openssh-server
  - openssh-sftp-server
  - openssl
  - os-prober
  - overlayroot
  - parted
  - pass
  - passwd
  - pastebinit
  - patch
  - pax
  - pciutils
  - perl
  - perl-base
  - perl-modules-5.26
  - pigz
  - pinentry-curses
  - policykit-1
  - pollinate
  - popularity-contest
  - powermgmt-base
  - procps
  - psmisc
  - publicsuffix
  - qrencode
  - readline-common
  - rpm
  - rpm-common
  - rpm2cpio
  - rsync
  - rsyslog
  - run-one
  - screen
  - sed
  - sensible-utils
  - shared-mime-info
  - simpleproxy
  - snapd
  - software-properties-common
  - sosreport
  - squashfs-tools
  - ssh-import-id
  - strace
  - sudo
  - systemd
  - systemd-sysv
  - sysvinit-utils
  - tar
  - tcpdump
  - telnet
  - time
  - tmux
  - tree
  - tzdata
  - ubuntu-keyring
  - ubuntu-minimal
  - ubuntu-release-upgrader-core
  - ubuntu-server
  - ubuntu-standard
  - ucf
  - udev
  - ufw
  - uidmap
  - unattended-upgrades
  - unzip
  - update-manager-core
  - update-notifier-common
  - ureadahead
  - usbutils
  - util-linux
  - uuid-runtime
  - vim
  - vim-common
  - vim-runtime
  - vim-tiny
  - virtualenv
  - wget
  - whiptail
  - x11-common
  - x11-utils
  - x11proto-core-dev
  - x11proto-dev
  - xauth
  - xclip
  - xdelta3
  - xdg-user-dirs
  - xfsprogs
  - xkb-data
  - xtrans-dev
  - xxd
  - xz-utils
  - zlib1g
  - zlib1g-dev
python_packages:
  - libpython-all-dev
  - libpython-dev
  - libpython-stdlib
  - libpython2.7
  - libpython2.7-dev
  - libpython2.7-minimal
  - libpython2.7-stdlib
  - libpython3-dev
  - libpython3-stdlib
  - libpython3.6
  - libpython3.6-dev
  - libpython3.6-minimal
  - libpython3.6-stdlib
  - python
  - python-all
  - python-all-dev
  - python-apt
  - python-apt-common
  - python-asn1crypto
  - python-backports.ssl-match-hostname
  - python-cached-property
  - python-certifi
  - python-cffi-backend
  - python-chardet
  - python-crypto
  - python-cryptography
  - python-dbus
  - python-dev
  - python-docker
  - python-dockerpty
  - python-dockerpycreds
  - python-docopt
  - python-enum34
  - python-funcsigs
  - python-functools32
  - python-gi
  - python-idna
  - python-ipaddress
  - python-jsonschema
  - python-keyring
  - python-keyrings.alt
  - python-minimal
  - python-mock
  - python-openssl
  - python-pbr
  - python-pip
  - python-pip-whl
  - python-pkg-resources
  - python-requests
  - python-secretstorage
  - python-setuptools
  - python-six
  - python-texttable
  - python-urllib3
  - python-virtualenv
  - python-websocket
  - python-wheel
  - python-xdg
  - python-yaml
  - python2.7
  - python2.7-dev
  - python2.7-minimal
  - python3
  - python3-apport
  - python3-apt
  - python3-asn1crypto
  - python3-attr
  - python3-automat
  - python3-blinker
  - python3-certifi
  - python3-cffi-backend
  - python3-chardet
  - python3-click
  - python3-colorama
  - python3-commandnotfound
  - python3-configobj
  - python3-constantly
  - python3-crypto
  - python3-cryptography
  - python3-dbus
  - python3-debconf
  - python3-debian
  - python3-dev
  - python3-distro-info
  - python3-distupgrade
  - python3-distutils
  - python3-gdbm
  - python3-gi
  - python3-httplib2
  - python3-hyperlink
  - python3-idna
  - python3-incremental
  - python3-jinja2
  - python3-json-pointer
  - python3-jsonpatch
  - python3-jsonschema
  - python3-jwt
  - python3-keyring
  - python3-keyrings.alt
  - python3-lib2to3
  - python3-markupsafe
  - python3-minimal
  - python3-netifaces
  - python3-newt
  - python3-oauthlib
  - python3-openssl
  - python3-pam
  - python3-pip
  - python3-pkg-resources
  - python3-problem-report
  - python3-pyasn1
  - python3-pyasn1-modules
  - python3-requests
  - python3-requests-unixsocket
  - python3-secretstorage
  - python3-serial
  - python3-service-identity
  - python3-setuptools
  - python3-six
  - python3-software-properties
  - python3-systemd
  - python3-twisted
  - python3-twisted-bin
  - python3-update-manager
  - python3-urllib3
  - python3-virtualenv
  - python3-wheel
  - python3-xdg
  - python3-yaml
  - python3-zope.interface
  - python3.6
  - python3.6-dev
  - python3.6-minimal
ruby_packages:
  - libruby2.5
  - rake
  - ruby
  - ruby-bundler
  - ruby-dev
  - ruby-did-you-mean
  - ruby-minitest
  - ruby-molinillo
  - ruby-net-http-persistent
  - ruby-net-telnet
  - ruby-power-assert
  - ruby-test-unit
  - ruby-thor
  - ruby2.5
  - ruby2.5-dev
  - ruby2.5-doc
  - rubygems-integration
