---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: inspec
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist:
        - yaml
        - profile_tasks
      bin_ansible_callbacks:
        - yaml
      stdout_callback: yaml
      interpreter_python: python3
verifier:
  name: inspec
  lint:
    name: rubocop
